# Generated by Django 4.1.1 on 2022-09-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_estudiantes_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=60),
        ),
    ]
